---
# tasks file for onr-prometheus-nodexp
- name: Ensure installation directory exists - 
  file:
    path: "{{ onr_prometheus_nodexp_install_folder }}"
    state: directory

- name: Download node exporter release binary
  get_url:
    url: "{{ onr_prometheus_nodexp_binary_url }}"
    dest: "{{ onr_prometheus_nodexp_install_folder }}/{{ onr_prometheus_nodexp_binary_name }}"
    mode: 0740


    