---
# tasks file for onr-prometheus-nodexp
- name: Ensure installation directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ onr_prometheus_nodexp_install_folder }}"

- name: Download node exporter release binary
  get_url:
    url: "{{ onr_prometheus_nodexp_binary_url }}"
    dest: "{{ onr_prometheus_nodexp_install_folder }}/{{ onr_prometheus_nodexp_binary_name }}.tgz"

- name: Extract node exporter archive to installation folder
  unarchive:
    src: "{{ onr_prometheus_nodexp_install_folder }}/{{ onr_prometheus_nodexp_binary_name }}.tgz"
    dest: "{{ onr_prometheus_nodexp_install_folder }}"
    remote_src: yes

- name: Make sure node_exporter is executable
  file:
    path: "{{ onr_prometheus_nodexp_install_folder }}/{{ onr_prometheus_nodexp_binary_name }}/node_exporter"
    mode: '0740'

- name: Ensure systemd directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ onr_prometheus_nodexp_systemd_folder }}"
  when: onr_prometheus_nodexp_systemd_enable

- name: Upload System D Service File
  template:
    src: nodexp.service
    dest: "{{ onr_prometheus_nodexp_systemd_folder }}/nodexp.service"
  when: onr_prometheus_nodexp_systemd_enable

#systemd module can't handle custom unit file path
- name: Enable node exporter service
  shell: systemctl enable {{ onr_prometheus_nodexp_systemd_folder }}/nodexp.service
  args:
    chdir: "{{ onr_prometheus_nodexp_systemd_folder }}"
  become: yes

- name: Enable and start node exporter service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: nodexp.service
  when: onr_prometheus_nodexp_systemd_enable
  become: yes
    